# Generated by Django 4.2 on 2024-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('id',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Описание урока', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, help_text='Картинка урока', null=True, upload_to='course/preview', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='урок', help_text='Название урока', max_length=500, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео', null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Описание курса', null=True, verbose_name='Описание'),
        ),
    ]
