# Generated by Django 4.2 on 2024-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_lesson_options_rename_name_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, help_text='Картинка урока', null=True, upload_to='lesson/preview', verbose_name='Картинка'),
        ),
    ]
