# Generated by Django 4.2 on 2024-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Цена курса'),
        ),
    ]
