# Generated by Django 4.2 on 2024-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.SmallIntegerField(default=1000, verbose_name='Цена курса'),
        ),
    ]
